# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        place:
            properties:
                id: ~
                title: { boost: 4 }
                description: { boost: 2 }
                address: ~
                city: { boost: 3 }
                postalCode: ~
                country: ~
                ratings: ~
                influx: ~
                types: ~
            persistence:
                driver: orm
                model: App\Domain\Place\Entity\Place
                listener: ~
